name: Update Vector Store and Generate Alerts

on:
  push:
    paths:
      - 'data/raw/**'
      - 'data/processed/**'
      - 'data/vector_db/**'
      - 'data/**/*.dvc'
  pull_request:
    paths:
      - 'data/raw/**'
      - 'data/processed/**'
      - 'data/vector_db/**'
      - 'data/**/*.dvc'
  workflow_dispatch:  # Allow manual trigger

jobs:
  update-vectors:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'
          cache: 'pip'
      
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install dvc
      
      - name: Configure DVC
        run: |
          dvc config core.autostage true
          mkdir -p .dvc/tmp
      
      - name: Update vector store and generate alerts
        run: |
          python update_vector_store.py
      
      - name: Check for generated alerts
        run: |
          if [ -d "alerts" ]; then
            echo "Alerts directory exists, checking for alert files"
            ls -la alerts/
            alert_count=$(find alerts -name "alerts_*.json" | wc -l)
            echo "Found $alert_count alert files"
          else
            echo "No alerts directory found"
          fi
      
      - name: Commit alert changes
        if: success()
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add alerts/
          git commit -m "Auto-generate alerts from data changes" || echo "No changes to commit"
          git push 